# DAG-Healer (https://github.com/cesarzea/dag-healer)
# Copyright (c) 2026 César Pedro Zea Gómez (https://www.cesarzea.com)
# SPDX-License-Identifier: MIT

[pytest]
testpaths = tests
addopts = -ra
filterwarnings =
    ignore::DeprecationWarning
